name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger via the Actions tab

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: TanushreeHarika
          outputs: |
            dist/github-contribution-grid-snake.svg?speed=8&color=bd93f9
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&speed=13&color=ff79c6&head=bd93f9

      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
